### ISSUE TITLE
Respect .editorconfig indent size

### ISSUE THREAD

**Issue by farskid** [tierratelematics/code-beautifier#6]
Hi
Thanks for the extension.
I use `.editorconfig` file in my projects and set tabsSize and indent Size to 2.
After I installed the extension, I used `Cmd + Shift + F` to beatify my _sass_ code and your extension reformatted my sass with tabsize 4.
I also tried to changed editor.tabSize and beatify.tabSize to 2 but it didn't help.

**Comment by sant123** [comment]
Any progress in this issue?

**Comment by guoyunhe** [comment]
Want this feature too!

**Comment by farskid** [comment]
@sant123 @guoyunhe I moved on to using prettier and it just works awesome!

**Comment by mike7515** [comment]
Fixed in 2.0.3

**Comment by Maximaximum** [comment]
The issue has NOT been fixed, it still reproduces with scss files in v2.0.3, nothing changed for me

**Comment by yblondeau** [comment]
Depending on your config, a possible workaround is to set `beautify.tabSize` to the same value as `indent_size` in your `.editorconfig` file.

**Comment by farskid** [comment]
@yblondeau Thank you. But these days, I only use Prettier and I'm happy :)
